# Linear Algebra in Python

In [1]:
import numpy as np

# Solve the following equation of systems for the values of x and y:
2x + 3y = 8\
5x + 4y = 20

In [2]:
# Cofficient of matrix A
A = np.array([[2, 3], [5, 4]])
A


array([[2, 3],
       [5, 4]])

In [7]:
# konstant matrix B
B = np.array([8, 20])
B

array([ 8, 20])

In [8]:
# Solve for x
x = np.linalg.solve(A, B)
x

array([4., 0.])

In [9]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
b

array([[1., 2., 3.],
       [3., 4., 5.]])

In [12]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a, a.shape, a.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 (2, 5),
 2)

In [15]:
a[:, 2] = 20
a


array([[ 1,  2, 20, 20,  5],
       [ 6,  7, 20, 20, 10]])

In [16]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.full_like(a, 100)


array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
output = np.zeros((7,7))
output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
z = np.ones((5, 5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
z[2, 2] = 5
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 5., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
output[1:-1, 1:-1] = z
output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [29]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
b = np.max(a, axis=1).sum()
b

15

In [31]:
b = np.max(a, axis=0).sum()
b

40

In [33]:
a  = np.ones((4, 2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
# save numbers in a txt file
a = [29, 97, 32, 100, 45,
     15, 88, 5, 75, 22]
np.savetxt('test.txt', a, delimiter=',')
a

[29, 97, 32, 100, 45, 15, 88, 5, 75, 22]

In [ ]:
d = [29, 97, 32, 100, 45
     15, 88, 5, 75, 22]
d = pd.to_csv('data.txt')

In [41]:
a = np.genfromtxt('test1.txt', delimiter=',')
a, a.shape, a.ndim

(array([[ 29.,  97.,  32., 100.,  45.,   1.,   2.,   3.],
        [ 15.,  88.,   5.,  75.,  22.,   4.,   5.,   6.],
        [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.]]),
 (3, 8),
 2)

In [42]:
b = a.astype('int32')
b

array([[ 29,  97,  32, 100,  45,   1,   2,   3],
       [ 15,  88,   5,  75,  22,   4,   5,   6],
       [  1,   2,   3,   4,   5,   6,   7,   8]])

In [43]:
b > 50

array([[False,  True, False,  True, False, False, False, False],
       [False,  True, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [44]:
b[b > 50]

array([ 97, 100,  88,  75])

In [46]:
d = np.genfromtxt('test.txt', delimiter=',')
d

array([[ 29.,  97.,  32., 100.,  45.],
       [ 15.,  88.,   5.,  75.,  22.]])

In [48]:
e = d.astype('int16')
e

array([[ 29,  97,  32, 100,  45],
       [ 15,  88,   5,  75,  22]], dtype=int16)

In [49]:
d > 50

array([[False,  True, False,  True, False],
       [False,  True, False,  True, False]])

In [51]:
d[d < 50]

array([29., 32., 45., 15.,  5., 22.])

# Creating a kalkulator for statistikal parameters.

In [114]:
# def. fun.
def calculate(num_list):
    num_array = np.array(num_list)
    if num_array.size != 9:
        raise ValueError('List must contain nine numbers.')
    else:
        mat = np.array(num_array).reshape(3,3)
        
        # kalkulating mean
        mean = np.mean(mat).tolist()
        mean_axis0 = np.mean(mat, axis=0).tolist()
        mean_axis1 = np.mean(mat, axis=1).tolist()
        
        #kalkulating var
        var = np.var(mat).tolist()
        var_axis0 = np.var(mat, axis=0).tolist()
        var_axis1 = np.var(mat, axis=1).tolist()
        
        #std
        std = np.std(mat).tolist()
        std_axis0 = np.std(mat, axis=0).tolist()
        std_axis1 = np.std(mat, axis=1).tolist()
        
        #max
        max = np.max(mat).tolist()
        max_axis0 = np.max(mat, axis=0).tolist()
        max_axis1 = np.max(mat, axis=1).tolist()
        
        #min
        min = np.min(mat).tolist()
        min_axis0 = np.min(mat, axis=0).tolist()
        min_axis1 = np.min(mat, axis=1).tolist()
        
        #sum
        sum = np.sum(mat).tolist()
        sum_axis0 = np.sum(mat, axis=0).tolist()
        sum_axis1 = np.sum(mat, axis=1).tolist()
        
        stat_dict = {
            'mean': [mean_axis0, mean_axis1, mean],
            'variance': [var_axis0, var_axis1, var],
            'standard deviation': [std_axis0, std_axis1, std],
            'max': [max_axis0, max_axis1, max],
            'min': [min_axis0, min_axis1, min],
            'sum': [sum_axis0, sum_axis1, sum]
    }
    return stat_dict

In [115]:
# Kalling fun.

# num_array = np.random.randint(1, 11, 9)
num_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(f'array:{num_array},', 'data type:', num_array.dtype)
num_list = num_array.tolist()
print(f'list: {num_list},', 'data type:', type(num_list))

stat_dict = calculate(num_list) 
stat_dict

array:[0 1 2 3 4 5 6 7 8], data type: int32
list: [0, 1, 2, 3, 4, 5, 6, 7, 8], data type: <class 'list'>


{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [105]:
mat = np.random.randint(1, 9, (3,3))
sum = np.sum(mat).tolist()
sum_axis0 = np.sum(mat, axis=0).tolist()
sum_axis1 = np.sum(mat, axis=1).tolist()
mat, sum, sum_axis0, sum_axis1

(array([[2, 1, 7],
        [5, 8, 5],
        [2, 4, 4]]),
 38,
 [9, 13, 16],
 [10, 18, 10])

In [106]:
l = [sum, sum_axis0, sum_axis1]
l

[38, [9, 13, 16], [10, 18, 10]]

In [ ]:
# konvet array into list


 

